export const UPDATE_TABLE_DATA  = 'UPDATE_TABLE_DATA';
export const UPDATE_MATCHING_PERCENTAGE = 'UPDATE_MATCHING_PERCENTAGE';
export const UPDATE_COUNTRY_ORIGIN = 'UPDATE_COUNTRY_ORIGIN';
export const UPDATE_RISK_LEVEL = 'UPDATE_RISK_LEVEL';
export const UPDATE_WATCH_LIST = 'UPDATE_WATCH_LIST';
export const UPDATE_PEP_CLASS = 'UPDATE_PEP_CLASS';
export const UPDATE_FROM_DATE = 'UPDATE_FROM_DATE';
export const UPDATE_TO_DATE = 'UPDATE_TO_DATE';
export const UPDATE_TABLE_HEADING = 'UPDATE_TABLE_HEADING';





